# Generated by Django 5.2.13 on 2026-04-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_activated',
        ),
    ]
