# Generated by Django 5.2.13 on 2026-05-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_client_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='client',
        ),
        migrations.AddField(
            model_name='user',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.client', verbose_name='Доступные клиенты'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='external_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='external_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
