# Generated by Django 5.2.13 on 2026-05-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_client_id_order_address_order_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('confirmed', 'Подтвержден'), ('rejected', 'Отклонен'), ('done', 'Выполнен')], default='draft', max_length=20),
        ),
    ]
