# Generated by Django 5.2.13 on 2026-05-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
