# Generated by Django 5.2.13 on 2026-05-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_product_client_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_name',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255),
        ),
    ]
