# Generated by Django 5.2.13 on 2026-05-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='preview_img',
            field=models.ImageField(blank=True, null=True, upload_to='img/products/preview'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='img/products/original', verbose_name='Изображение'),
        ),
    ]
