# Generated by Django 5.2.13 on 2026-05-21 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_client_address_clientaddress'),
        ('orders', '0013_productimage_preview_img_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='client',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.CreateModel(
            name='ClientPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, max_length=10, verbose_name='Индивидуальная цена')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_prices', to='accounts.client', verbose_name='Клиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_prices', to='orders.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Индивидуальная цена клиента',
                'verbose_name_plural': 'Индивидуальные цены клиентов',
                'unique_together': {('client', 'product')},
            },
        ),
    ]
