# Generated by Django 5.2.13 on 2026-06-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_product_article_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(choices=[(0, 'Банковский перевод'), (1, 'Наличные')], default=0),
        ),
    ]
