# Generated by Django 5.2.13 on 2026-09-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_product_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_code',
            field=models.CharField(default='', max_length=64),
        ),
    ]
