# Generated by Django 5.2.13 on 2026-09-03 14:57

from django.db import migrations

# Generated by Django 5.2.13 on 2026-09-03 14:49

from django.db import migrations


def migrate_products(apps, schema_editor):
    OrderItem = apps.get_model("orders", "OrderItem")
    Product = apps.get_model("orders", "Product")

    for item in OrderItem.objects.all().iterator():
        product = Product.objects.filter(product_id = item.product_id).first()

        if product is not None:
            item.product_code = product.article
            item.save(update_fields=["product_code"])
        

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_orderitem_product_code'),
    ]

    operations = [
        migrations.RunPython(migrate_products),
    ]
